# Generated by Django 2.2 on 2021-03-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.FileField(blank=True, null=True, upload_to='profile_pictures', verbose_name='profile picture')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('is_pinned', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('action', models.CharField(choices=[('pending', 'Pending'), ('on-going', 'On going'), ('completed', 'Completed')], default='pending', max_length=50, null=True)),
                ('td_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='core.TodoList')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
