# Generated by Django 2.2 on 2021-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='action',
            field=models.CharField(choices=[('on-going', 'On going'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=50, null=True),
        ),
    ]
