# Generated by Django 2.2 on 2021-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todoitem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='action',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-going', 'On going'), ('completed', 'Completed')], default='pending', max_length=50, null=True),
        ),
    ]
