# Generated by Django 2.2 on 2021-03-04 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210304_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
