# Generated by Django 2.2 on 2021-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210222_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfields',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
