# Generated by Django 2.2 on 2021-03-04 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_todolist_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
