# Generated by Django 2.2 on 2021-02-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todolist_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-date_updated']},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='status',
        ),
    ]
