# Generated by Django 2.2 on 2021-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210224_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_pinned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
