# Generated by Django 2.2 on 2021-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfields',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
