# Generated by Django 2.2 on 2021-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210224_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfields',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commonfields',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
