# Generated by Django 2.2 on 2021-03-01 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210301_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='profile_pictures', verbose_name='profile picture'),
            preserve_default=False,
        ),
    ]
