# Generated by Django 2.2 on 2021-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(null=True, upload_to='profile_pictures', verbose_name='profile picture'),
        ),
    ]
