# Generated by Django 2.2 on 2021-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210301_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures', verbose_name='profile picture'),
        ),
    ]
