# Generated by Django 2.2 on 2021-03-02 16:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210302_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[core.validators.validate_mobile]),
        ),
    ]
